### ISSUE TITLE
Add support for query parameters

### ISSUE THREAD

**Issue by MarkusBansky** [MarkusBansky/react-redux-generator#7]
Add support for query parameters in the url.

Currently no parameters are supported. Expected to be able to support fury parameter structure for example:

```yml
- name: email         
  in: query 
  description: The email of the account to search for. All accounts matching part of the email will be returned 
  required: false 
  schema: 
    type: string
```

this code should generate a specific variable in the typescript function definition of the action:

````typescript
const someAction = (/**...**/, email?: string, /**...**/): any => //.....
````

- [x] Should be able to support `string` types of query parameters
- [x] Should be able to support `number` types of query parameters
- [x] Should be able to support `any` and TS typed query parameters
- [x] Should be able to support optional query parameters, sorted by this attribute
